### PR TITLE
Update AI-102

### PR DESCRIPTION
**Pull request by mctjon**
# Module: 00
## Lab/Demo: 00

Fixes # .

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Review by GraemeMalcolm — CHANGES_REQUESTED** [review]
Thanks for submitting!
The typo fixes in the Computer Vision and Form Recognizer labs are fine, but the changes to the Azure Portal UI don't seem to be right - the button to add a resource group when in the Resource Groups blade is +Add, not +Create; and when viewing the Test Bot in Portal blade, the link to the channels page (under Settings in the pane on the left) is "Channels", not "Connect to Channels".

**Comment by mctjon** [comment]
Graeme,

Here is a screenshot of the resource group page with +Create on it.  I would have to recreate the lab to grab a screenshot of the Connect to Channels.

Jon
________________________________

**Comment by GraemeMalcolm** [comment]
Can't see a screenshot attachment in your message, but are you sure you're not looking at the HOME page rather than the RESOURCE GROUPS page (which is what the instructions assume)?
Screenshots for both UI elements attached
add-rg
bot-channels

**Comment by mctjon** [comment]
Graeme,

[cid:764f66b6-062f-42d6-8d8b-d29ea2b48ea6]
________________________________

**Comment by GraemeMalcolm** [comment]
@mctjon 
Posting by email doesn't appear to be working (at least, I can't see your comments fully). Any chance you could comment directly in  the pull request (https://github.com/MicrosoftLearning/AI-102-AIEngineer/pull/54)?

Thanks!

**Comment by GraemeMalcolm** [comment]
So it seems the Azure portal UI is inconsistent - possibly by region.
I'm rewording the instructions to make them more generic.

**Pull request merged**
