### PR TITLE
Change to new sentiment scoring

### PR DESCRIPTION
**Pull request by madiepev**
## Lab/Demo: 22-Create-a-search-solution

Changes proposed in this pull request:

- Change modify-search to retrieve sentiment label instead of sentiment score.
- Change Python web page template to visualize sentiment label instead of score.
- Change C# web page to visualize sentiment label instead of score.

### CODE REVIEW

**Review by GraemeMalcolm — CHANGES_REQUESTED** [review]
In the skillset definition, the sentiment skill has to be of type #Microsoft.Skills.Text.V3.SentimentSkill (you've used the original version - not v3)

**Comment by madiepev** [comment]
Fixed

**Review by GraemeMalcolm — CHANGES_REQUESTED** [review]
Looks good - everything works for me for the first exercise.
You'll need to update the JSON files used by the setup script in the second and third exercises to reflect the v3 sentiment skill. Add those changes to this PR and then we'll merge them as a single update.

**Review by GraemeMalcolm — CHANGES_REQUESTED** [review]
Can you delete the **obj** / **debug** folders that get created on compilation for the C# app?

**Comment by madiepev** [comment]
@GraemeMalcolm could you check if everything's ok now?

**Comment by GraemeMalcolm** [comment]
Looks good - merged!

**Pull request merged**
